# Generated by Django 5.0.6 on 2024-05-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_contactos', '0002_alter_contacto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='apodo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='direccion_trabajo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='subfijo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
